# Generated by Django 5.0.9 on 2024-11-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='stipe_id',
            new_name='stripe_id',
        ),
    ]
