# Generated by Django 5.0.9 on 2024-11-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0007_subscription_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='permission',
        ),
        migrations.AddField(
            model_name='subscription',
            name='permissions',
            field=models.ManyToManyField(limit_choices_to={'codename__icontains': 'basic', 'content_type__app_label': 'subscriptions'}, to='auth.permission'),
        ),
    ]
