name: 1 - Hello World Github actions

on:
  workflow_dispatch:

  # schedule:
  #   - cron: '30 15 * * *'
  # crontab.guru - above runs at 15:30 every day

  # below runs every time git push
  # push: #git push
  #   branch:
  #     - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Hello there
      run: echo "hello"